apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observo-client-cluster-role
  labels:
    app: observo-client
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"] 