{{- if .Values.image.pullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ecr-pull-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .Values.image.pullSecret.token }}"
{{- end }} 